environment: development

apphost: k8s

label:
  name: mnenntestweb

container:
  name: mnenntestweb-container
  pullPolicy: IfNotPresent
  image: mnenntestwebapp-dev
  tag: v1
  port: 80

replicas: 1

service:
  port: 5004
  type: ClusterIP
