apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnenn-test-web
spec:
  selector:
    matchLabels:
      app: mnenn-test-web
  template:
    metadata:
      labels:
        app: mnenn-test-web
    spec:
      containers:
      - name: mnenn-test-web
        image: mnenn-kub:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mnenn-test-service
  labels:
    apps: mnenn-test-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 5003
      targetPort: 80
      name: mnenn-test-service
  selector:
    app: mnenn-test-web